remote_theme: eliottvincent/bay

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: db758@cornell.edu
      link: mailto:db758@cornell.edu
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/debasmita-bhattacharya-9583a2154/
    
header:
  pages:
    - name: Home
      slug: index.md     # <-- index.md
    - name: Research  # <-- blog.md
    - name: Misc  # <-- whatever.md
