remote_theme: eliottvincent/bay

title: DB | Columbia CS
url: "https://d-bhattacharya.github.io" # the base hostname & protocol for the site

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: debasmita.b@cs.columbia.edu
      link: mailto:debasmita.b@cs.columbia.edu
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/debasmita-bhattacharya-9583a2154/
    - name: Twitter
      link: https://twitter.com/debasmitab_
    
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Research # <-- research.md
    - name: Teaching  # <-- teaching.md
